Telemetry data sending
GateNLP/gate-teamware pull request #270
Opened 2022-12-15 10:45 UTC by davidwilby

This PR includes:
* Sending of telemetry data for completing and deleting projects.
* Adds a module for managing telemetry.
* Overrides the `delete` method for the `Project` model.
* Adds settings for telemetry.
* Adds tests for the telemetry module.

Currently the URL for the post requests is just a placeholder of course.

2022-12-23 18:03 UTC, twinkarma requested changes
The code's looking good to me. Only a couple of minor changes as discussed in the meeting.

2023-01-09 15:41 UTC, davidwilby commented on backend/models.py
> +            self.send_telemetry(status="complete")
Thanks for spotting this. Resolved by [218e53e](https://github.com/GateNLP/gate-teamware/pull/270/commits/218e53ed26e889d0fd3440b07067b67c7297e293)

2023-01-11 13:50 UTC, davidwilby commented
Waiting on recieving server to be up, so we can include the URL here.

2023-02-15 13:46 UTC, twinkarma approved these changes

2023-02-15 13:47 UTC, merged