Dynamic options for checkbox/radio/selector
GateNLP/gate-teamware pull request #303
Opened 2023-03-03 12:42 UTC by ianroberts

Implementing a mechanism to take checkbox/radio/selector options from the document as well as from the static project configuration, to allow for things like entity disambiguation tasks where the list of possible options varies from document to document.

The initial implementation is based on a new type of entry in the `options` array, so as well as

```json
{"value": "some-value", "label": "Some value"}
```

we now support

```json
{"fromDocument": "someProperty"}
```

which in turn expects `someProperty` in the document JSON to have the same form as the original `options` configuration itself (either an array of `value`/`label` objects, or a dictionary mapping values to labels).  For convenience I've also added support for an array of plain strings, where a string `"X"` is treated as if it were `{"value": "X", "label": "X"}`.

Closes #289

2023-03-03 12:43 UTC, ianroberts commented
I've created this as a draft so I can ask for feedback on the idea in principle before I attempt to add the "delimited" format that I've mentioned in #289.

2023-03-03 13:40 UTC, ianroberts commented on frontend/src/utils/annotations.js
> +                if (typeof option === 'string') {
Technically this bit also allows the list-of-strings format within the _project_ configuration directly, i.e.

```json
{"type":"checkbox", "name":"foo", "options":["option 1", "option 2"]}
```

but this should be rejected by the schema-driven JSON editor.

2023-03-06 14:32 UTC, twinkarma commented
A note from our recent discussion, from my understanding the behaviour of `fromDocument` is :

```{"fromDocument": "someProperty"}```

if `someProperty` is:
* An object/dictionary - works exactly the same as default behavior
   ```
          { // The options can be specified as a dictionary, ordering is not guaranteed
              "value1": "Text to show user 1",
              "value2": "Text to show user 2",
              "value3": "Text to show user 3"
          }
    ```
* An array of objects - works the same as the default behavior and expects the following structure:
   ```
  [ // The options that the user is able to select from
        {"value": "value1", "label": "Text to show user 1"},
        {"value": "value2", "label": "Text to show user 2"},
        {"value": "value3", "label": "Text to show user 3"}
    ], 
  ```
* An array of string - The string is used for both label and value
* A single string, will look for a delimiter (`;` by default) to separate the options e.g. `value1;value2`
  * You can define your own delimiter and separator in the `fromDocument` option e.g.
    ```{"fromDocument:"someProperty", "separator":":", "delimiter":";"}``` to do a key value split of the string (separator is blank/disabled by default).

2023-03-06 14:59 UTC, twinkarma commented
Not sure what the default combination of separators & delimiters makes the most sense though. Should we be detecting only delimiters `;` by default or should we be doing separator & delimiters (`:` and `;`)? 

Thinking about it, I'd imagine in most cases people would want to do the second case more often?

2023-03-08 23:31 UTC, ianroberts commented
I've implemented the delimited string option now, with the default delimiters being `;` between options and `=` between the value and label of a single option, i.e.

    apple=Apples; orange=Oranges; kiwi=Kiwi fruit

The between-options delimiter can be overridden by specifying `separator` and the value-label separator by `valueLabelSeparator` (slightly clunky name but I didn't want to use terminology like "key-value" as that implies the "value" is the right hand half of each pair when in Teamware terms it's the left half).

```json
{"fromDocument": "options", "separator": "~~", "valueLabelSeparator": "::"}
```

    apple::Apples ~~ orange::Oranges ~~ kiwi=Kiwi fruit

(Note I've also made it `.trim()` every sub-string after splitting, so spaces around any delimiter are ignored)

2023-03-09 17:24 UTC, twinkarma requested changes
I've tried this out and it's working for me! 

Can you add an example document.json and project configuration.json to the `examples` folder?

Here's an example of one I made to test the feature based on your documentation:

```
[
  {
    "id": "1",
    "text": "Testing options specified with array of dictionary",
    "options": [
      {"value": "val1","label":  "Object label 1"},
      {"value": "val2","label":  "Object label 2"},
      {"value": "val3","label":  "Object label 3"}
    ]

  },
  {
    "id": "2",
    "text": "Testing options specified with array of dictionary",
    "options": {
      "val1": "Key value label 1",
      "val2": "Key value label 2",
      "val3": "Key value label 3"
    }
  },
  {
    "id": "3",
    "text": "Testing options specified with array of string",
    "options": [
      "String array label 1", "String array label 2", "String array label 3"
    ]
  },
  {
    "id": "4",
    "text": "Testing options specified with a single string, separated using special characters (= and ; by default)",
    "options": "val1=Separator label 1;val2=Separator label  2;val3=Separator label  3"
  },
  {
    "id": "5",
    "text": "Testing options specified with a custom separator (:: and ~~ in this case)",
    "options": "val1::Custom separator label 1~~val2::Custom separator label 2~~val3::Custom separator label 3"
  }
]
```

2023-03-09 23:49 UTC, ianroberts commented
I've added the examples you requested, and also improved the documentation more generally so we consistently use the array style (that preserves order) rather than dict style (that doesn't) for all checkbox & radio samples except the section that specifically introduces the dict style as an alternative.

2023-03-10 14:56 UTC, twinkarma approved these changes
Looks good to me!

2023-03-10 14:57 UTC, merged